spring:
  mainDB:
    database:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:multi-db-main;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  subDB:
    database:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:multi-db-sub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
server:
  port: 9999
